Map<String, dynamic> testAirfieldData = {
  "datetime": "01-18-2021 | 08:51:28 (Z)",
  "data": [
    {
      "airfield": "Bobby",
      "status": "LIMOP",
      "be": "PQ7002",
      "airdiv": 3,
      "rw": "NONOP",
      "tw": "NONOP",
      "ugf": "OP",
      "pol": "LIMOP",
      "ms": "LIMOP",
      "rf": "LIMOP"
    },
    {
      "airfield": "Nemesis",
      "status": "NONOP",
      "be": "MO1689",
      "airdiv": 2,
      "rw": "LIMOP",
      "tw": "NONOP",
      "ugf": "OP",
      "pol": "NONOP",
      "ms": "NONOP",
      "rf": "OP"
    },
    {
      "airfield": "Zeus",
      "status": "NONOP",
      "be": "AP6931",
      "airdiv": 4,
      "rw": "LIMOP",
      "tw": "OP",
      "ugf": "NONOP",
      "pol": "OP",
      "ms": "NONOP",
      "rf": "LIMOP"
    },
    {
      "airfield": "Hephaestus",
      "status": "LIMOP",
      "be": "UB8405",
      "airdiv": 4,
      "rw": "LIMOP",
      "tw": "NONOP",
      "ugf": "NONOP",
      "pol": "OP",
      "ms": "NONOP",
      "rf": "LIMOP"
    },
    {
      "airfield": "Nyx",
      "status": "LIMOP",
      "be": "CZ2702",
      "airdiv": 2,
      "rw": "OP",
      "tw": "LIMOP",
      "ugf": "LIMOP",
      "pol": "OP",
      "ms": "NONOP",
      "rf": "NONOP"
    },
    {
      "airfield": "Hyperion",
      "status": "LIMOP",
      "be": "ND4226",
      "airdiv": 4,
      "rw": "LIMOP",
      "tw": "LIMOP",
      "ugf": "NONOP",
      "pol": "OP",
      "ms": "NONOP",
      "rf": "OP"
    },
    {
      "airfield": "Demeter",
      "status": "NONOP",
      "be": "WL4063",
      "airdiv": 2,
      "rw": "LIMOP",
      "tw": "LIMOP",
      "ugf": "NONOP",
      "pol": "LIMOP",
      "ms": "LIMOP",
      "rf": "LIMOP"
    },
    {
      "airfield": "Aphrodite",
      "status": "LIMOP",
      "be": "CD2313",
      "airdiv": 3,
      "rw": "OP",
      "tw": "NONOP",
      "ugf": "LIMOP",
      "pol": "OP",
      "ms": "NONOP",
      "rf": "LIMOP"
    },
    {
      "airfield": "Chronos",
      "status": "OP",
      "be": "UL8984",
      "airdiv": 1,
      "rw": "OP",
      "tw": "LIMOP",
      "ugf": "LIMOP",
      "pol": "NONOP",
      "ms": "LIMOP",
      "rf": "LIMOP"
    },
    {
      "airfield": "Tartarus",
      "status": "NONOP",
      "be": "LU2573",
      "airdiv": 2,
      "rw": "OP",
      "tw": "LIMOP",
      "ugf": "NONOP",
      "pol": "NONOP",
      "ms": "NONOP",
      "rf": "LIMOP"
    },
    {
      "airfield": "Ares",
      "status": "LIMOP",
      "be": "MU6949",
      "airdiv": 4,
      "rw": "NONOP",
      "tw": "LIMOP",
      "ugf": "NONOP",
      "pol": "NONOP",
      "ms": "NONOP",
      "rf": "NONOP"
    },
    {
      "airfield": "Hestia",
      "status": "LIMOP",
      "be": "PM8231",
      "airdiv": 1,
      "rw": "OP",
      "tw": "OP",
      "ugf": "LIMOP",
      "pol": "NONOP",
      "ms": "NONOP",
      "rf": "LIMOP"
    },
    {
      "airfield": "Artemis",
      "status": "NONOP",
      "be": "RL5642",
      "airdiv": 4,
      "rw": "OP",
      "tw": "OP",
      "ugf": "OP",
      "pol": "LIMOP",
      "ms": "OP",
      "rf": "NONOP"
    },
    {
      "airfield": "Hypnos",
      "status": "NONOP",
      "be": "GI6665",
      "airdiv": 2,
      "rw": "NONOP",
      "tw": "LIMOP",
      "ugf": "OP",
      "pol": "OP",
      "ms": "LIMOP",
      "rf": "NONOP"
    },
    {
      "airfield": "Atlas",
      "status": "LIMOP",
      "be": "BF0395",
      "airdiv": 1,
      "rw": "NONOP",
      "tw": "NONOP",
      "ugf": "NONOP",
      "pol": "LIMOP",
      "ms": "NONOP",
      "rf": "LIMOP"
    },
    {
      "airfield": "Dionysus",
      "status": "LIMOP",
      "be": "FB1727",
      "airdiv": 2,
      "rw": "LIMOP",
      "tw": "OP",
      "ugf": "LIMOP",
      "pol": "NONOP",
      "ms": "LIMOP",
      "rf": "OP"
    },
    {
      "airfield": "Apollo",
      "status": "NONOP",
      "be": "WP2480",
      "airdiv": 3,
      "rw": "NONOP",
      "tw": "LIMOP",
      "ugf": "OP",
      "pol": "LIMOP",
      "ms": "OP",
      "rf": "OP"
    },
    {
      "airfield": "Phanes",
      "status": "OP",
      "be": "NB6378",
      "airdiv": 4,
      "rw": "OP",
      "tw": "OP",
      "ugf": "NONOP",
      "pol": "NONOP",
      "ms": "OP",
      "rf": "NONOP"
    },
    {
      "airfield": "Eros",
      "status": "OP",
      "be": "LX5248",
      "airdiv": 3,
      "rw": "OP",
      "tw": "OP",
      "ugf": "LIMOP",
      "pol": "NONOP",
      "ms": "OP",
      "rf": "NONOP"
    },
    {
      "airfield": "Hades",
      "status": "NONOP",
      "be": "TD3942",
      "airdiv": 4,
      "rw": "LIMOP",
      "tw": "OP",
      "ugf": "OP",
      "pol": "OP",
      "ms": "OP",
      "rf": "OP"
    },
    {
      "airfield": "Chaos",
      "status": "NONOP",
      "be": "LQ9220",
      "airdiv": 2,
      "rw": "NONOP",
      "tw": "OP",
      "ugf": "OP",
      "pol": "LIMOP",
      "ms": "NONOP",
      "rf": "LIMOP"
    },
    {
      "airfield": "Thanatos",
      "status": "OP",
      "be": "AY3831",
      "airdiv": 1,
      "rw": "NONOP",
      "tw": "OP",
      "ugf": "OP",
      "pol": "OP",
      "ms": "OP",
      "rf": "LIMOP"
    },
    {
      "airfield": "Hermes",
      "status": "OP",
      "be": "QL8809",
      "airdiv": 4,
      "rw": "LIMOP",
      "tw": "NONOP",
      "ugf": "NONOP",
      "pol": "NONOP",
      "ms": "NONOP",
      "rf": "OP"
    },
    {
      "airfield": "Hera",
      "status": "OP",
      "be": "CY5749",
      "airdiv": 1,
      "rw": "LIMOP",
      "tw": "OP",
      "ugf": "LIMOP",
      "pol": "NONOP",
      "ms": "NONOP",
      "rf": "OP"
    },
    {
      "airfield": "Athena",
      "status": "OP",
      "be": "HE5157",
      "airdiv": 2,
      "rw": "LIMOP",
      "tw": "NONOP",
      "ugf": "NONOP",
      "pol": "OP",
      "ms": "LIMOP",
      "rf": "LIMOP"
    }
  ]
};
